apiVersion: v1
kind: Service
metadata:
  name: redis-stack
  namespace: sandee
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30016  # Change this value
  selector:
    app.kubernetes.io/name: redis

