---
apiVersion: v1
kind: Namespace
metadata:
  name: sandee
  labels:
    name: sandee
    app.kubernetes.io/name: sandee
    app.kubernetes.io/instance: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: aws-load-balancer-controller
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
