apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app: aws-load-balancer-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-load-balancer-controller
  template:
    metadata:
      labels:
        app: aws-load-balancer-controller
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      serviceAccountName: aws-load-balancer-controller
      containers:
      - name: controller
        image: public.ecr.aws/eks/aws-load-balancer-controller:v2.7.2
        args:
        - --cluster-name=sandee
        - --ingress-class=alb
        - --aws-vpc-id=vpc-02f40ee7a414a4512
        - --aws-region=us-east-1
        - --enable-shield=false
        - --enable-waf=false
        - --enable-wafv2=false
        env:
        - name: AWS_VPC_ID
          value: "vpc-02f40ee7a414a4512"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 61779
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 61779
          initialDelaySeconds: 10
          timeoutSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux