apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::838645860193:role/AmazonEKSLoadBalancerControllerRole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app: aws-lb-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-lb-controller
  template:
    metadata:
      labels:
        app: aws-lb-controller
    spec:
      serviceAccountName: aws-load-balancer-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: controller
        image: public.ecr.aws/eks/aws-load-balancer-controller:v2.7.2
        args:
        - --cluster-name=sandee
        - --ingress-class=alb
        - --aws-vpc-id=vpc-02f40ee7a414a4512
        - --aws-region=us-east-1
        env:
        - name: AWS_VPC_ID
          value: "vpc-02f40ee7a414a4512"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 61779
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: 61779
          initialDelaySeconds: 10
      nodeSelector:
        kubernetes.io/os: linux