apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  # Allow large uploads
  proxy-body-size: "10g"

  # Timeout settings
  proxy-connect-timeout: "600"
  proxy-send-timeout: "600"
  proxy-read-timeout: "600"

  # Buffering
  proxy-buffering: "off"

  # Rewrite & regex support
  use-regex: "true"

  # Don't force SSL here (ALB already terminates SSL)
  ssl-redirect: "false"
  force-ssl-redirect: "false"

  # Hide NGINX version
  server-tokens: "false"
