# ALB Ingress for External Traffic
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandee-alb
  namespace: sandee
spec:
  ingressClassName: nginx
  rules:
  - host: eks.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sandee-frontend
            port:
              number: 80
  - host: www.eks.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sandee-frontend
            port:
              number: 80
  - host: eks-backend.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sandee-backend
            port:
              number: 8008
  - host: eks-admin.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sandee-admin
            port:
              number: 3000