apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandee-admin
  namespace: sandee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sandee-admin
  template:
    metadata:
      labels:
        app: sandee-admin
    spec:
      containers:
      - name: admin
        image: 838645860193.dkr.ecr.us-east-1.amazonaws.com/admin:latest
        ports:
        - containerPort: 3000
