apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandee-admin
  namespace: sandee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sandee-admin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: sandee-admin
    spec:
      containers:
      - name: admin
        image: 838645860193.dkr.ecr.us-east-1.amazonaws.com/admin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

