apiVersion: v1
kind: Service
metadata:
  name: sandee-backend
  namespace: sandee
spec:
  type: NodePort
  ports:
  - nodePort: 30003
    port: 8008
    targetPort: 8008
  selector:
    app: sandee-backend

