apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandee-backend
  namespace: sandee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sandee-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sandee-backend
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: NODE_ENV
          value: production
        image: 838645860193.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8008
