apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandee-frontend-alb-ingress
  namespace: sandee
  annotations:
    kubernetes.io/ingress.class: alb                                  # Specifies to use the AWS ALB Ingress Controller
    alb.ingress.kubernetes.io/scheme: internet-facing                 # Makes the ALB internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'          # Configures the ALB to listen on HTTP only (port 80)
    alb.ingress.kubernetes.io/load-balancer-attributes: "routing.http2.enabled=true"  # Enables HTTP/2 on ALB over HTTP
    alb.ingress.kubernetes.io/backend-protocol: HTTP                  # Configures ALB to communicate with backend over HTTP
    alb.ingress.kubernetes.io/healthcheck-path: "/health"             # Health check path (adjust based on your app)
    alb.ingress.kubernetes.io/healthcheck-port: "3000"                # Health check port for backend service
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "20"      # Health check interval (in seconds)
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"        # Health check timeout
    alb.ingress.kubernetes.io/healthcheck-healthy-threshold: "3"      # Healthy threshold for ALB
    alb.ingress.kubernetes.io/healthcheck-unhealthy-threshold: "2"    # Unhealthy threshold for ALB
spec:
  ingressClassName: alb                                               # Specifies ALB as the ingress controller
  rules:
  - host: eks.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sandee-frontend
            port:
              number: 3000

