apiVersion: v1
kind: Service
metadata:
  name: sandee-cron
  namespace: sandee
spec:
  type: NodePort
  ports:
  - nodePort: 30070
    port: 5001
    targetPort: 5001
  selector:
    app: sandee-cron
