apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
  namespace: sandee-staging
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/elastic
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-192-168-12-99.ec2.internal  # Replace with your actual node name

