apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: sandee
spec:
  type: NodePort
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 30005
  - name: transport
    port: 9300
    targetPort: 9300
    nodePort: 30004
  selector:
    app: elasticsearch
