apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
  namespace: sandee
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/elastic"
