apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandee-frontend
  namespace: sandee
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sandee-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: sandee-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sandee-frontend
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: sandee-frontend
      containers:
      - name: frontend
        image: 838645860193.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
        imagePullPolicy: Always
        env:
        - name: NEXT_PUBLIC_DEV_BASE_URL
          value: http://sandee-backend:8008/api/v1
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
