apiVersion: v1
kind: Service
metadata:
  name: sandee-frontend
  namespace: sandee-staging
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
  selector:
    app: sandee-frontend
