apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandee-frontend
  namespace: sandee
spec:
  replicas: 6
  selector:
    matchLabels:
      app: sandee-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: sandee-frontend
    spec:
      containers:
      - name: frontend
        image: 838645860193.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
        imagePullPolicy: Always
        env:
        - name: NEXT_PUBLIC_DEV_BASE_URL
          value: http://sandee-backend:8008/api/v1
        ports:
        - containerPort: 3000

