apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sandee-backend-hpa
  namespace: sandee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sandee-backend  # <-- Target your backend deployment
  minReplicas: 4
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Scale when CPU usage >50%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # Scale when Memory usage >70%

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sandee-frontend-hpa
  namespace: sandee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sandee-frontend  # <-- Target your frontend deployment
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Scale when CPU usage >50%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # Scale when Memory usage >70%

