apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sandee-backend-hpa
  namespace: sandee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sandee-backend
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sandee-frontend-hpa
  namespace: sandee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sandee-frontend
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-hpa
  namespace: sandee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: elasticsearch-hpa
  namespace: sandee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: elasticsearch
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
