apiVersion: v1
kind: ConfigMap
metadata:
  name: postgis-script
  namespace: sandee-staging
data:
  init_postgis.sh: |
    #!/bin/bash
    echo "Creating PostGIS extension"
    psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE EXTENSION IF NOT EXISTS postgis;"
    echo "Granting superuser permissions"
    psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "ALTER USER postgres WITH SUPERUSER;"
    psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "ALTER USER postgres WITH SUPERUSER;"
