apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sandee-staging
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres

