apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-new
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0439d0e0f127e5ec4
    fsType: ext4
  storageClassName: gp3
  persistentVolumeReclaimPolicy: Retain
