apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: sandee
data:
  local-redis-stack.conf: |
    bind 0.0.0.0
    protected-mode no
    loadmodule /opt/redis-stack/lib/rediscompat.so
    loadmodule /opt/redis-stack/lib/redisearch.so
    loadmodule /opt/redis-stack/lib/redistimeseries.so
    loadmodule /opt/redis-stack/lib/rejson.so
    loadmodule /opt/redis-stack/lib/redisbloom.so
    loadmodule /opt/redis-stack/lib/redisgears.so v8-plugin-path /opt/redis-stack/lib/libredisgears_v8_plugin.so
    replica-read-only no
    maxmemory 6gb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    dbfilename dump.rdb
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    loglevel warning
    logfile "/data/redis.log"
    tcp-keepalive 60
    # Enable slow log
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    # Optimize networking
    tcp-backlog 511
    # Disable unnecessary features for performance
    latency-monitor-threshold 0
    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
    lazyfree-lazy-server-del yes
    # Ensure persistence safety
    stop-writes-on-bgsave-error yes
