apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-new
  namespace: sandee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3
