apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: sandee
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10g"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Force SSL redirection
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - sandee.com
      - eks-admin.sandee.com
      - admin.sandee.com
      - eks-backend.sandee.com
      - backend-v2.sandee.com
      - eks-redis.sandee.com
      - eks-elasticsearch.sandee.com
    secretName: sandee-tls  # Your TLS secret covering all hosts
  rules:
  - host: sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sandee-frontend
            port:
              number: 3000
  - host: eks-admin.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sandee-admin
            port:
              number: 3000
  - host: admin.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sandee-admin
            port:
              number: 3000
  - host: eks-backend.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sandee-backend
            port:
              number: 8008
  - host: backend-v2.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sandee-backend
            port:
              number: 8008
  - host: eks-redis.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redis
            port:
              number: 6379
  - host: eks-elasticsearch.sandee.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch
            port:
              number: 9200

