apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-stack-config
  namespace: sandee
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: redis-stack-helm
    meta.helm.sh/release-namespace: sandee
data:
  redis-stack.conf: |
    bind 0.0.0.0
    protected-mode no
    loadmodule /opt/redis-stack/lib/redisearch.so
    loadmodule /opt/redis-stack/lib/rejson.so
    loadmodule /opt/redis-stack/lib/redisbloom.so
    loadmodule /opt/redis-stack/lib/redistimeseries.so
    maxmemory 6gb
    maxmemory-policy noeviction
    save 60 1000
    save 300 100
    dbfilename dump.rdb
    dir /data
    appendonly yes
    appendfsync everysec
    slowlog-max-len 1024
    hz 100
