---
apiVersion: v1
kind: Service
metadata:
  name: redis-stack-master
  namespace: sandee
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31016  # ✅ Unique Master NodePort
  selector:
    app.kubernetes.io/name: redis-stack-master

---
apiVersion: v1
kind: Service
metadata:
  name: redis-stack-replica
  namespace: sandee
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31017  # ✅ Unique Replica NodePort
  selector:
    app.kubernetes.io/name: redis-stack-replica
