global:
  storageClass: "redis-storage-class"

architecture: replication  # ✅ Enables Master-Replica setup

auth:
  enabled: false  # No authentication (Change to `true` if needed)

image:
  repository: redis/redis-stack  # ✅ Use Redis Stack image
  tag: latest

master:
  nameOverride: redis-stack-master
  persistence:
    enabled: true
    path: /data  # ✅ Ensure Redis writes to the correct directory
    size: 20Gi
    storageClass: redis-storage-class  # ✅ Use correct StorageClass
  resources:
    requests:
      memory: "3Gi"
      cpu: "500m"
    limits:
      memory: "5Gi"
      cpu: "1800m"

  extraArgs:
    - "--dir /data"
    - "--dbfilename dump.rdb"
    - "--appendonly yes"
    - "--appendfsync everysec"
    - "--save 60 1000 300 100"  # ✅ Enable RDB snapshot every 60s if 1000 writes occur
    - "--repl-backlog-size 10mb"
    - "--repl-diskless-sync yes"
    - "--repl-diskless-sync-delay 5"
    - "--maxclients 10000"

  extraVolumes:
    - name: redis-stack-master-config
      configMap:
        name: redis-stack-master-config

  extraVolumeMounts:
    - name: redis-stack-master-config
      mountPath: /opt/redis-stack/etc/redis-stack-master.conf
      subPath: redis-stack-master.conf
    - name: redis-data
      mountPath: /data  # ✅ Mount /data for persistent storage

replica:
  nameOverride: redis-stack-replica
  replicaCount: 2  # ✅ Increased for redundancy
  persistence:
    enabled: true
    path: /data  # ✅ Ensure Redis writes to the correct directory
    size: 10Gi
    storageClass: redis-storage-class
  resources:
    requests:
      memory: "3Gi"
      cpu: "500m"
    limits:
      memory: "5Gi"
      cpu: "1800m"

  extraArgs:
    - "--dir /data"
    - "--dbfilename dump.rdb"
    - "--appendonly yes"
    - "--appendfsync everysec"
    - "--save 60 1000 300 100"  # ✅ Enable RDB snapshot every 60s if 1000 writes occur
    - "--repl-diskless-sync yes"  # ✅ Enable diskless sync to reduce I/O impact
    - "--repl-diskless-sync-delay 5"  # ✅ Delay sync start to improve stability
    - "--maxclients 10000"

  extraVolumes:
    - name: redis-stack-replica-config
      configMap:
        name: redis-stack-replica-config

  extraVolumeMounts:
    - name: redis-stack-replica-config
      mountPath: /opt/redis-stack/etc/redis-stack-replica.conf
      subPath: redis-stack-replica.conf
    - name: redis-data
      mountPath: /data  # ✅ Mount /data for persistent storage

sentinel:
  enabled: true  # ✅ Enable Redis Sentinel for automatic failover
  quorum: 2  # ✅ Number of votes needed to trigger failover
  replicas: 2

service:
  master:
    type: ClusterIP
  replica:
    type: ClusterIP
  sentinel:
    type: ClusterIP
