apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: sandee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: redis-storage-class

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: sandee
data:
  redis-master.conf: |
    bind 0.0.0.0
    protected-mode no
    loadmodule /opt/redis-stack/lib/rediscompat.so
    loadmodule /opt/redis-stack/lib/redisearch.so
    loadmodule /opt/redis-stack/lib/redistimeseries.so
    loadmodule /opt/redis-stack/lib/rejson.so
    loadmodule /opt/redis-stack/lib/redisbloom.so
    loadmodule /opt/redis-stack/lib/redisgears.so v8-plugin-path /opt/redis-stack/lib/libredisgears_v8_plugin.so
    replica-read-only no
    maxmemory 4gb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    dbfilename dump.rdb
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    loglevel warning
    logfile "/data/redis.log"
    tcp-keepalive 300
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    tcp-backlog 511
    latency-monitor-threshold 0
    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
    lazyfree-lazy-server-del yes
    stop-writes-on-bgsave-error yes

  redis-replica.conf: |
    bind 0.0.0.0
    protected-mode no
    loadmodule /opt/redis-stack/lib/rediscompat.so
    loadmodule /opt/redis-stack/lib/redisearch.so
    loadmodule /opt/redis-stack/lib/redistimeseries.so
    loadmodule /opt/redis-stack/lib/rejson.so
    loadmodule /opt/redis-stack/lib/redisbloom.so
    loadmodule /opt/redis-stack/lib/redisgears.so v8-plugin-path /opt/redis-stack/lib/libredisgears_v8_plugin.so
    replica-read-only yes
    replicaof redis-master 6379
    maxmemory 4gb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    dbfilename dump.rdb
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    loglevel warning
    logfile "/data/redis.log"
    tcp-keepalive 300
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    tcp-backlog 511
    latency-monitor-threshold 0
    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
    lazyfree-lazy-server-del yes
    stop-writes-on-bgsave-error yes

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: sandee
data:
  sentinel.conf: |
    port 26379
    sentinel monitor mymaster redis-master.sandee.svc.cluster.local 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 10000
    sentinel parallel-syncs mymaster 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: sandee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - name: redis-master
        image: redis/redis-stack-server:latest
        command:
        - redis-server
        - /etc/redis-master.conf
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis-master.conf
          subPath: redis-master.conf
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
      - name: redis-config
        configMap:
          name: redis-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  namespace: sandee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-replica
  template:
    metadata:
      labels:
        app: redis-replica
    spec:
      containers:
      - name: redis-replica
        image: redis/redis-stack-server:latest
        command:
        - redis-server
        - /etc/redis-replica.conf
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis-replica.conf
          subPath: redis-replica.conf
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
      - name: redis-config
        configMap:
          name: redis-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: sandee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
      - name: redis-sentinel
        image: redis/redis-stack-server:latest
        command:
        - sh
        - -c
        - >
          cp /data/sentinel.conf /tmp/sentinel.conf && 
          redis-server /tmp/sentinel.conf --sentinel
        volumeMounts:
        - name: sentinel-config
          mountPath: /data/sentinel.conf
          subPath: sentinel.conf
        ports:
        - containerPort: 26379
      volumes:
      - name: sentinel-config
        configMap:
          name: redis-sentinel-config

---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: sandee
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30006
  selector:
    app: redis-master

---
apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  namespace: sandee
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30008
  selector:
    app: redis-replica

---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: sandee
spec:
  type: NodePort
  ports:
  - port: 26379
    targetPort: 26379
    nodePort: 30007
  selector:
    app: redis-sentinel
