apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: sandee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: redis-storage-class

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: sandee
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    loadmodule /opt/redis-stack/lib/rediscompat.so
    loadmodule /opt/redis-stack/lib/redisearch.so
    loadmodule /opt/redis-stack/lib/redistimeseries.so
    loadmodule /opt/redis-stack/lib/rejson.so
    loadmodule /opt/redis-stack/lib/redisbloom.so
    maxmemory 6gb
    maxmemory-policy volatile-lru
    maxmemory-samples 5


    save 60 1000
    save 300 100
    rdbcompression yes
    dbfilename dump.rdb
    dir /data

    # AOF Persistence
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync always
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes

    # Logging and Performance
    loglevel notice
    logfile "/data/redis.log"
    tcp-keepalive 60
    tcp-backlog 2048
    io-threads 4
    io-threads-do-reads yes
    slowlog-log-slower-than 10000
    slowlog-max-len 1024
    latency-monitor-threshold 0
    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
    lazyfree-lazy-server-del yes
    stop-writes-on-bgsave-error yes
    hz 100
    dynamic-hz yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: sandee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: redis
        image: redis/redis-stack-server:latest
        command:
        - redis-server
        - /etc/redis/redis.conf
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            memory: "3Gi"
            cpu: "1000m"
          limits:
            memory: "6Gi"
            cpu: "2"
        ports:
        - containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
      - name: redis-config
        configMap:
          name: redis-config
---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sandee
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30006
  selector:
    app: redis

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
