apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandee-backend
  namespace: sandee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandee-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: sandee-backend
    spec:
      containers:
      - name: backend
        image: 838645860193.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: NODE_ENV
          value: production
        ports:
        - containerPort: 8008
        resources:
          requests:
            cpu: "20m"
            memory: "100Mi"
